name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.0
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist/website
          BUILD_SCRIPT: npm install && npm run build -- --prod